const swaggerDoc = {
  info: {
    version: "1.0.5",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:8090",
  basePath: "/",
  schemes: ['https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "Configuracion",
      "description": "Endpoints para la configuración de la aplicación"
    }
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",
      name: "X-API-KEY",
      description: "any description..."
    }
  }
};

module.exports = swaggerDoc;